### ISSUE TITLE
bug: absolute paths aren't supported within flux kustomizations

### ISSUE THREAD

**Issue by lrstanley** [allenporter/flux-local#407]
Using 03ca70f4c5fe8972bdce22c616e822284087dc27 (current HEAD), it looks as though flux-local doesn't support absolute paths within the `kustomize.toolkit.fluxcd.io/v1` / `Kustomization` CRD. FluxCD does support absolute paths, where root would be the repository root.

I'm unable to share my flux repo directly, so hopefully the following information will suffice.

Repo structure, all flux related items are under `/flux` from the root of the repository:

```console
$ tree
.
├── [...]
├── flux
│   ├── apps
│   │   └── [...]
│   ├── clusters
│   │   └── ovh
│   │       ├── bootstrap
│   │       │   ├── bootstrap.yaml
│   │       │   └── flux-system
│   │       │       ├── gotk-components.yaml
│   │       │       ├── gotk-sync.yaml
│   │       │       └── kustomization.yaml
│   │       └── deployments
│   │           └── kustomization.yaml
│   └── manifests
│       └── [...]
└── terraform
    └── [...]
```

`flux/clusters/ovh/bootstrap/bootstrap.yaml` contents, which looks to be the problem file:

```console
$ cat flux/clusters/ovh/bootstrap/bootstrap.yaml
# Helm repositories
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-repositories
  namespace: flux-system
spec:
  path: /flux/manifests/helm-repositories
  prune: true
  interval: 1h
  timeout: 5m
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  decryption:
    provider: sops
    secretRef:
      name: sops-keys

---
# [...]
```

`path: /flux/manifests/helm-repositories` being the culprit.

Exception:

```console
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py", line 493, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py", line 115, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py", line 152, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/pluggy/_result.py", line 114, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py", line 77, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/src/flux_local/tool/test.py", line 280, in pytest_sessionstart
INTERNALERROR>     asyncio.run(self.async_pytest_sessionstart(session))
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 31, in run
INTERNALERROR>     return loop.run_until_complete(task)
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 99, in run_until_complete
INTERNALERROR>     return f.result()
INTERNALERROR>   File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result
INTERNALERROR>     raise self._exception.with_traceback(self._exception_tb)
INTERNALERROR>   File "/usr/lib/python3.10/asyncio/tasks.py", line 232, in __step
INTERNALERROR>     result = coro.send(None)
INTERNALERROR>   File "/src/flux_local/tool/test.py", line 285, in async_pytest_sessionstart
INTERNALERROR>     manifest = await git_repo.build_manifest(
INTERNALERROR>   File "/src/flux_local/git_repo.py", line 533, in build_manifest
INTERNALERROR>     results = await kustomization_traversal(selector.path)
INTERNALERROR>   File "/src/flux_local/git_repo.py", line 387, in kustomization_traversal
INTERNALERROR>     docs = await grep_fluxtomizations(selector.root, path)
INTERNALERROR>   File "/src/flux_local/git_repo.py", line 315, in grep_fluxtomizations
INTERNALERROR>     await kustomize.grep(f"kind={CLUSTER_KUSTOMIZE_KIND}", root / relative_path)
INTERNALERROR>   File "/src/flux_local/kustomize.py", line 130, in objects
INTERNALERROR>     return [doc async for doc in self._docs(target_namespace=target_namespace)]
INTERNALERROR>   File "/src/flux_local/kustomize.py", line 130, in <listcomp>
INTERNALERROR>     return [doc async for doc in self._docs(target_namespace=target_namespace)]
INTERNALERROR>   File "/src/flux_local/kustomize.py", line 120, in _docs
INTERNALERROR>     out = await self.run()
INTERNALERROR>   File "/src/flux_local/kustomize.py", line 114, in run
INTERNALERROR>     return await run_piped(self._cmds)
INTERNALERROR>   File "/src/flux_local/command.py", line 117, in run_piped
INTERNALERROR>     result = await _run_piped_with_sem(cmds)
INTERNALERROR>   File "/src/flux_local/command.py", line 109, in _run_piped_with_sem
INTERNALERROR>     out = await asyncio.wait_for(cmd.run(stdin), _TIMEOUT)
INTERNALERROR>   File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
INTERNALERROR>     return fut.result()
INTERNALERROR>   File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result
INTERNALERROR>     raise self._exception.with_traceback(self._exception_tb)
INTERNALERROR>   File "/usr/lib/python3.10/asyncio/tasks.py", line 232, in __step
INTERNALERROR>     result = coro.send(None)
INTERNALERROR>   File "/src/flux_local/command.py", line 82, in run
INTERNALERROR>     proc = await asyncio.create_subprocess_shell(
INTERNALERROR>   File "/usr/lib/python3.10/asyncio/subprocess.py", line 205, in create_subprocess_shell
INTERNALERROR>     transport, protocol = await loop.subprocess_shell(
INTERNALERROR>   File "/usr/lib/python3.10/asyncio/base_events.py", line 1648, in subprocess_shell
INTERNALERROR>     transport = await self._make_subprocess_transport(
INTERNALERROR>   File "/usr/lib/python3.10/asyncio/unix_events.py", line 207, in _make_subprocess_transport
INTERNALERROR>     transp = _UnixSubprocessTransport(self, protocol, args, shell,
INTERNALERROR>   File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 36, in __init__
INTERNALERROR>     self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
INTERNALERROR>   File "/usr/lib/python3.10/asyncio/unix_events.py", line 799, in _start
INTERNALERROR>     self._proc = subprocess.Popen(
INTERNALERROR>   File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
INTERNALERROR>     self._execute_child(args, executable, preexec_fn, close_fds,
INTERNALERROR>   File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
INTERNALERROR>     raise child_exception_type(errno_num, err_msg, err_filename)
INTERNALERROR> FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/flux/manifests/helm-repositories')
```

As for potential solutions, could likely check if the path is absolute, and if absolute, join `<git worktree root> + <absolute path>`. Where worktree root could be calculated from `git rev-parse --show-toplevel` or similar.

**Comment by allenporter** [comment]
Thank you for the detailed report. As a next step, we can set up a test cluster configured this way in https://github.com/allenporter/flux-local/tree/main/tests/testdata and attempt to reproduce the issue locally, then determine an appropriate fix.

I suspect the fix will be to modify the path to make it a relative path in https://github.com/allenporter/flux-local/blob/03ca70f4c5fe8972bdce22c616e822284087dc27/flux_local/git_repo.py#L347 since while the path is an absolute path, it's not really. Not entirely sure though, will look closer.
